server:
  port: 8000

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      server:
        webflux:
          # 전역 필터 설정
          default-filters:
            - AddRequestHeader=X-Gateway-Request, true
          
          # 개별 서비스 라우팅 전략
          routes:
            - id: user-server
              uri: lb://USER-SERVER
              predicates:
                - Path=/api/v1/users/**
              filters:
                - name: CustomAuthFilter

            - id: delivery-server
              uri: lb://DELIVERY-SERVER
              predicates:
                - Path=/api/v1/deliveries/**
              filters:
                - name: CustomAuthFilter

            - id: hub-server
              uri: lb://HUB-SERVER
              predicates:
                - Path=/api/v1/hubs/**
              filters:
                - name: CustomAuthFilter

            - id: order-server
              uri: lb://ORDER-SERVER
              predicates:
                - Path=/api/v1/orders/**
              filters:
                - name: CustomAuthFilter

            - id: vendor-server
              uri: lb://VENDOR-SERVER
              predicates:
                - Path=/api/v1/vendors/**
              filters:
                - name: CustomAuthFilter

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/